### ISSUE TITLE
what if multiple user with same name is there

### ISSUE THREAD

**Issue by RiteshKSingh1729** [kr-prince/Flask-SocketIO-ChatApp#2]
https://github.com/kr-prince/Flask-SocketIO-ChatApp/blob/47c692ea6a96da1397d7df146b8296a04c6e1911/mainApp.py#L62

l = ["ram","shayam","laxmi","ram"] 
l.remove("ram") will remove first element, It would be better if we assign the id to each name to avoid this issue.

**Comment by kr-prince** [comment]
@RiteshKSingh1729  Good point. I have kept it as part of TODOs for now. Working on it. Feel free to add.

**Comment by kr-prince** [comment]
@RiteshKSingh1729 Some changes were done. For the sake of simplicity, the username used for joining the chat is being restricted to be unique in the chat room, I am considering it to be an identifier itself for now.
